name: Test
run-name: Testing FlexIni scripts 🚀
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  Test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install newer bash on macOS
        if: matrix.os == 'macos-latest'
        run: brew install bash
      - name: Run tests
        run: |
          if [[ "$(uname)" == "Darwin" ]]; then
            /opt/homebrew/bin/bash ./tests/_run.sh
          else
            bash ./tests/_run.sh
          fi
      - run: echo "🍏 This job's status is ${{ job.status }}."
