name: Test
run-name: Testing FlexIni scripts 🚀
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  Test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Check bash version
        run: bash check_bash_version.sh
      - run: bash ./tests/_run.sh
        shell: bash
      - run: echo "🍏 This job's status is ${{ job.status }}."
